# 配置文件版本
ver: 3

#启用统计信息
bStats: true

# 是否取消发送默认的加入消息
notSendJoinMessage: true

# 第一次加入全服播报
firstJoinMessage:
  - "[新玩家加入] &b {player}"

# 第二次及之后加入播报
JoinMessage:
  - "你好&b&l{player}&r 欢迎来到服务器"